# Generated by Django 4.2.30 on 2026-04-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Sequence', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Code', models.CharField(max_length=10)),
                ('ShortName', models.CharField(max_length=15)),
                ('StandardName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=250, null=True)),
                ('Remarks', models.CharField(max_length=250, null=True)),
                ('Active', models.BooleanField()),
                ('AddedBy', models.CharField(max_length=30, null=True)),
                ('AddedDate', models.DateTimeField(blank=True, null=True)),
                ('AddedFromIP', models.CharField(max_length=15, null=True)),
                ('UpdatedBy', models.CharField(max_length=30, null=True)),
                ('UpdatedDate', models.DateTimeField(blank=True, null=True)),
                ('UpdatedFromIP', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
