# Generated by Django 6.0 on 2026-04-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagelocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
