# Generated by Django 6.0 on 2026-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storagelocations', '0002_alter_storagelocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='Code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='Sequence',
            field=models.IntegerField(auto_created=True),
        ),
    ]
