# Generated by Django 6.0 on 2026-04-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storagelocations', '0002_alter_storagelocation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Sequence', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Code', models.CharField(max_length=10)),
                ('Rows', models.IntegerField()),
                ('Columns', models.CharField(max_length=10)),
                ('ShortName', models.CharField(max_length=15)),
                ('StandardName', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=250)),
                ('Remarks', models.CharField(max_length=250)),
                ('Active', models.BooleanField()),
                ('AddedBy', models.CharField(max_length=30)),
                ('AddedDate', models.DateTimeField()),
                ('UpdatedBy', models.CharField(max_length=30)),
                ('UpdatedDate', models.DateTimeField()),
                ('StorageLocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storagelocations', to='storagelocations.storagelocation')),
            ],
        ),
    ]
