# Generated by Django 6.0 on 2026-04-22 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racks', '0002_alter_rack_code_alter_rack_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sequence', models.IntegerField(auto_created=True)),
                ('UserName', models.CharField(max_length=30)),
                ('Code', models.CharField(max_length=10, unique=True)),
                ('Rows', models.IntegerField()),
                ('Columns', models.CharField(max_length=10)),
                ('AddedBy', models.CharField(max_length=30)),
                ('AddedDate', models.DateTimeField()),
                ('UpdatedBy', models.CharField(max_length=30)),
                ('UpdatedDate', models.DateTimeField()),
                ('RackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='racks.rack')),
            ],
        ),
    ]
